### ISSUE TITLE
Crossbuilding plans?

### ISSUE THREAD

**Issue by Katrix** [illyohs/Scorg#1]
What are your plans for crossbuilding for multiple scala versions in the future with this mod? Multiple mods depending on different versions of Scala can be a bit of a problem if they aren't shaded and relocated properly.

**Comment by 0xilly** [comment]
As it stands there's only plans for supporting the latest major release for scala there's no  support for 2.11.x and below or the current 2.13.x milestone releases. Ideally all mods should be using the same version of scala with forge. If the need for a special version arises I could make one but I think it would be better for us to stick to one version for now.

**Comment by 0xilly** [comment]
I should document this

**Comment by 0xilly** [comment]
Unless you mean shading this mod? This mod is meant to be drop in replacement for when native scala support is dropped from forge.

**Comment by 0xilly** [comment]
@Katrix- I reloaced the packages into scorg.scala
