### ISSUE TITLE
JitPack builds failing

### ISSUE THREAD

**Issue by TheReturningVoid** [illyohs/Scorg#3]
Builds from version 1.1.0 have failed to compile, leaving the latest avaliable version at 1.0.3. Not sure if you're aware of this already, just giving you a heads-up.

**Comment by 0xilly** [comment]
I know im not sure why it builds locally... I need to find a real maven so I can just deploy locally ill look into fixing it after I get home by next week

**Comment by 0xilly** [comment]
Build is fixed closing the issue.

_Sent from my Samsung SM-G930P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
